### ISSUE TITLE
 don't just concatenate trimmings

### ISSUE THREAD

**Issue by jmesserli** [M4R1KU/slack-svmeal#2]

**Comment by M4R1KU** [comment]
Please explain that better. Thanks.

**Comment by jmesserli** [comment]
Even though you know what I mean since you sat next to me when I opened this issue, I'll happily explain what I mean.

You are using [jmesserli/svmeal-api](https://github.com/jmesserli/svmeal-api) to fetch the meal plan data, which returns an array of "trimmings" for each meal available. You are just concatenating those with a space which makes the text a bit unreadable at times.

I suggest concatenating the trimmings with a dash ( - ) instead.

**Comment by M4R1KU** [comment]
Okay, thanks for your nice description.
I'll look into it.
I'll try some various delimiters to get the best out of the slack-app.

**Comment by M4R1KU** [comment]
@jmesserli So, I changed it to \n because with a dash it looks very weird.
You can try it in slack and give feedback.

**Comment by jmesserli** [comment]
@M4R1KU looks good to me! 😄
