### ISSUE TITLE
Date should be parsed and formatted

### ISSUE THREAD

**Issue by jmesserli** [M4R1KU/slack-svmeal#5]
![image](https://cloud.githubusercontent.com/assets/613138/19418581/200d30c8-93c7-11e6-9b9c-e601e6510e45.png)

The date should be in the format `dd.MM.yyyy`

**Comment by M4R1KU** [comment]
I think I fixed this. @jmesserli

**Comment by jmesserli** [comment]
Kind of

**Comment by M4R1KU** [comment]
You made this issue on the wrong repository btw.

**Comment by jmesserli** [comment]
Yeah I realized that yesterday 😂

Mario Kunz <notifications@github.com> schrieb am Fr., 3. März 2017, 08:21:
